name: PGQD Deployment to OpenShift

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-pgqd:
    runs-on: ubuntu-22.04
    name: Deploy PGQD

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0  # lock to a specific version

      - name: Install OC CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          echo "SHA256 CHECKING..."
          echo "your_expected_sha256_here  oc.tar.gz" | sha256sum -c -
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Authenticate to OpenShift
        run: |
          oc login --token="${{ secrets.OPENSHIFT_TOKEN }}" --server="${{ secrets.OPENSHIFT_SERVER }}"

      - name: Helm Lint & Dry Run
        run: |
          helm lint helm/pgqd
          helm template pgqd helm/pgqd --debug

      - name: Deploy PGQD using Helm
        run: |
          helm upgrade --install pgqd helm/pgqd --namespace pgqd --create-namespace

      - name: Verify Deployment Rollout
        run: |
          oc rollout status deployment/pgqd -n pgqd --timeout=60s

      - name: Verify Pods Status
        run: |
          oc get pods -n pgqd

      - name: Deployment Success Notification
        run: echo "✅ PGQD deployed successfully!"

    # Optional: On Failure
    continue-on-error: false

  notify-failure:
    if: failure()
    runs-on: ubuntu-latest
    needs: deploy-pgqd
    steps:
      - name: Notify Failure
        run: echo "❌ PGQD deployment failed!"
